
import { Pattern } from '@/types';

// Original handwritten patterns
const originalPatterns: Pattern[] = [
    {
        id: '1',
        creator_id: 'user1',
        designer_id: 'user1',
        source: 'original',
        title: { en: 'Cozy Cable Knit Sweater', ko: '아늑한 꽈배기 스웨터' },
        description: { en: 'A classic cable knit sweater perfect for fall. Features intricate cable patterns on the front and back with ribbed cuffs and hem.', ko: '가을에 딱 맞는 클래식한 꽈배기 스웨터. 앞뒤로 정교한 꽈배기 무늬가 있으며 고무뜨기 소매와 밑단이 특징입니다.' },
        thumbnail_url: 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=800&q=80',
        category: 'sweater',
        difficulty: 'intermediate',
        yarn_weight: ['worsted'],
        needle_size_mm: [5],
        techniques: ['cable'],
        gauge_stitches: 18,
        gauge_rows: 24,
        is_free: false,
        price_usd: 8.99,
        price_krw: 12000,
        pdf_url: null,
        preview_images: ['https://images.unsplash.com/photo-1620799140171-7138010ec997?w=400&q=80'],
        download_count: 1234,
        view_count: 5678,
        status: 'published',
        is_ai_generated: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: '2',
        creator_id: 'user2',
        designer_id: 'user2',
        source: 'original',
        title: { en: 'Nordic Snowflake Hat', ko: '노르딕 눈꽃 모자' },
        description: { en: 'Traditional Fair Isle pattern with snowflake motifs. Perfect for winter.', ko: '눈꽃 모티브의 전통 페어아일 패턴. 겨울에 딱 맞습니다.' },
        thumbnail_url: 'https://images.unsplash.com/photo-1576871337632-b9aef4c17ab9?w=800&q=80',
        category: 'hat',
        difficulty: 'advanced',
        yarn_weight: ['dk'],
        needle_size_mm: [4],
        techniques: ['colorwork'],
        gauge_stitches: 22,
        gauge_rows: 28,
        is_free: true,
        price_usd: null,
        price_krw: null,
        pdf_url: null,
        preview_images: [],
        download_count: 2345,
        view_count: 8901,
        status: 'published',
        is_ai_generated: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: '3',
        creator_id: 'user3',
        designer_id: 'user3',
        title: { en: 'Lace Summer Scarf', ko: '레이스 여름 스카프' },
        description: { en: 'Delicate lace pattern for light summer accessories.', ko: '가벼운 여름 액세서리를 위한 섬세한 레이스 패턴.' },
        thumbnail_url: 'https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?w=800&q=80',
        category: 'scarf',
        difficulty: 'intermediate',
        yarn_weight: ['lace', 'fingering'],
        needle_size_mm: [3.5],
        techniques: ['lace'],
        gauge_stitches: 28,
        gauge_rows: 36,
        is_free: false,
        price_usd: 5.99,
        price_krw: 8000,
        pdf_url: null,
        preview_images: [],
        download_count: 567,
        view_count: 2345,
        status: 'published',
        is_ai_generated: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: '4',
        creator_id: 'user4',
        designer_id: 'user4',
        title: { en: 'Baby Booties Set', ko: '아기 덧신 세트' },
        description: { en: 'Adorable booties for little feet.', ko: '작은 발을 위한 사랑스러운 덧신.' },
        thumbnail_url: 'https://images.unsplash.com/photo-1519457431-44ccd64a579b?w=800&q=80',
        category: 'other',
        difficulty: 'beginner',
        yarn_weight: ['sport'],
        needle_size_mm: [3.25],
        techniques: ['stockinette'],
        gauge_stitches: 24,
        gauge_rows: 32,
        is_free: true,
        price_usd: null,
        price_krw: null,
        pdf_url: null,
        preview_images: [],
        download_count: 4567,
        view_count: 12000,
        status: 'published',
        is_ai_generated: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: '5',
        creator_id: 'user5',
        designer_id: 'user5',
        title: { en: 'Brioche Scarf', ko: '브리오슈 스카프' },
        description: { en: 'Thick and squishy brioche stitch pattern.', ko: '두툼하고 푹신한 브리오슈 스티치 패턴.' },
        thumbnail_url: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=800&q=80',
        category: 'scarf',
        difficulty: 'advanced',
        yarn_weight: ['aran', 'bulky'],
        needle_size_mm: [6],
        techniques: ['brioche'],
        gauge_stitches: 14,
        gauge_rows: 20,
        is_free: false,
        price_usd: 6.99,
        price_krw: 9000,
        pdf_url: null,
        preview_images: [],
        download_count: 890,
        view_count: 3456,
        status: 'published',
        is_ai_generated: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: '6',
        creator_id: 'user6',
        designer_id: 'user6',
        title: { en: 'Geometric Blanket', ko: '기하학 무늬 담요' },
        description: { en: 'Modern geometric colorwork blanket.', ko: '모던한 기하학적 배색 담요.' },
        thumbnail_url: 'https://images.unsplash.com/photo-1589182373726-e4f658ab62f8?w=800&q=80',
        category: 'blanket',
        difficulty: 'intermediate',
        yarn_weight: ['worsted'],
        needle_size_mm: [5],
        techniques: ['colorwork', 'mosaic'],
        gauge_stitches: 18,
        gauge_rows: 24,
        is_free: false,
        price_usd: 12.99,
        price_krw: 17000,
        pdf_url: null,
        preview_images: [],
        download_count: 234,
        view_count: 1234,
        status: 'published',
        is_ai_generated: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
];

import ravelryPatternsData from '@/data/ravelry_patterns.json';

// Convert json data to Pattern objects
const ravelryPatterns: Pattern[] = ravelryPatternsData.map((p: any) => ({
    ...p,
    // Ensure designer_id exists
    designer_id: p.designer_id || p.creator_id || 'unknown',
    category: (['sweater', 'cardigan', 'hat', 'scarf', 'socks', 'mittens', 'blanket'].includes(p.category) ? p.category : 'sweater') as any,
    difficulty: (['beginner', 'intermediate', 'advanced'].includes(p.difficulty) ? p.difficulty : 'intermediate') as any,
}));

// Export combined patterns (Free Only)
export const allPatterns = [...originalPatterns, ...ravelryPatterns].filter(p => p.is_free);

export const getPatternById = (id: string): Pattern | null => {
    return allPatterns.find(p => p.id === id) || null;
};
