-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. PROFILES (Extends auth.users)
create table public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  display_name text,
  role text default 'knitter' check (role in ('knitter', 'designer', 'admin')),
  subscription_tier text default 'free' check (subscription_tier in ('free', 'pro')),
  avatar_url text,
  bio text,
  website_url text,
  instagram_handle text,
  credits integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS for Profiles
alter table public.profiles enable row level security;
create policy "Public profiles are viewable by everyone." on profiles for select using (true);
create policy "Users can insert their own profile." on profiles for insert with check (auth.uid() = id);
create policy "Users can update own profile." on profiles for update using (auth.uid() = id);

-- 2. PROPERTIES_DICTIONARY (Localization Mapping)
create table public.properties_dictionary (
  id bigint generated by default as identity primary key,
  term_key text unique not null,
  category text, -- e.g., 'action', 'noun', 'unit'
  en text not null,
  ko text,
  ja text,
  zh text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Seed basic dictionary data
insert into public.properties_dictionary (term_key, category, en, ko, ja, zh) values
('cast_on', 'action', 'Cast On', '코잡기', '作り目', '起针'),
('bind_off', 'action', 'Bind Off', '코막음', '伏せ目', '收针'),
('knit', 'action', 'Knit', '겉뜨기', '表編み', '下针'),
('purl', 'action', 'Purl', '안뜨기', '裏編み', '上针'),
('row', 'unit', 'Row', '단', '段', '行'),
('stitch', 'unit', 'Stitch', '코', '目', '针'),
('increase', 'action', 'Increase', '코늘림', '増し目', '加针'),
('decrease', 'action', 'Decrease', '코줄임', '減らし目', '减针'),
('yarn_over', 'action', 'Yarn Over', '바늘비우기', 'かけ目', '空针');

-- 3. PATTERNS (Marketplace)
create table public.patterns (
  id uuid default uuid_generate_v4() primary key,
  designer_id uuid references public.profiles(id),
  type text check (type in ('internal_pdf', 'external_link')) not null,
  title jsonb not null default '{}'::jsonb, -- { "en": "...", "ko": "..." }
  description jsonb default '{}'::jsonb,
  price_usd numeric default 0,
  file_path text, -- Supabase Storage path (null for external)
  origin_url text, -- For external links
  thumbnail_url text,
  images text[],
  is_watermarked boolean default false,
  category text, 
  subcategory text,
  difficulty text,
  craft_type text check (craft_type in ('knitting', 'crochet')), -- New: Craft Type
  yarn_weight text,
  yardage integer, -- e.g. 1200 (in meters)
  needles text,      -- e.g. '4.0mm, 3.5mm'
  gauge text,        -- e.g. '22sts/30rows'
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- RLS for Patterns
alter table public.patterns enable row level security;
create policy "Patterns are viewable by everyone." on patterns for select using (true);
create policy "Designers can insert own patterns." on patterns for insert with check (auth.uid() = designer_id);

-- 4. GRID_PROJECTS (SaaS Tools)
create table public.grid_projects (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references public.profiles(id) not null,
  title text not null default 'Untitled Project',
  grid_data jsonb not null, -- 2D array of grid cells (Now specific structure)
  gauge jsonb not null default '{"stitches": 10, "rows": 10}'::jsonb,
  palette jsonb default '{}'::jsonb, -- Color ID mapping
  width integer not null default 40,
  height integer not null default 40,
  original_image_url text,
  is_public boolean default false,
  project_type text default 'flat' check (project_type in ('flat', 'circular')),
  created_at timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- RLS for Grid Projects
alter table public.grid_projects enable row level security;
create policy "Users can CRUD own projects." on grid_projects for all using (auth.uid() = user_id);
create policy "Public projects viewable by everyone." on grid_projects for select using (is_public = true);

-- 5. ORDERS (Transactions)
create table public.orders (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references public.profiles(id) not null,
  pattern_id uuid references public.patterns(id) not null,
  amount numeric not null,
  currency text default 'USD',
  status text check (status in ('pending', 'paid', 'failed', 'refunded')) default 'pending',
  payment_provider text, -- 'portone', 'stripe'
  transaction_id text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- RLS for Orders
alter table public.orders enable row level security;
create policy "Users can view own orders." on orders for select using (auth.uid() = user_id);

-- 6. STITCH_SYMBOLS (Visual Dictionary)
create table public.stitch_symbols (
    id text primary key, -- e.g. 'knit', 'purl'
    icon_path text, -- SVG d string
    name jsonb not null, -- { "en": "Knit", "ko": "겉뜨기" }
    description jsonb, -- { "en": "...", "ko": "..." }
    antonym_id text references public.stitch_symbols(id), -- For Auto-Invert logic
    type text default 'basic' -- 'basic', 'cable', etc
);

-- Allow read access to everyone
alter table public.stitch_symbols enable row level security;
create policy "Symbols are viewable by everyone." on stitch_symbols for select using (true);

-- Seed Stitch Symbols
insert into public.stitch_symbols (id, name, description, antonym_id, type) values
(
    'knit', 
    '{"en": "Knit", "ko": "겉뜨기"}', 
    '{"en": "The most basic stitch. Looks like a V.", "ko": "가장 기본적인 뜨개 방법으로 V자 모양이 나옵니다."}', 
    null, 
    'basic'
),
(
    'purl', 
    '{"en": "Purl", "ko": "안뜨기"}', 
    '{"en": "The opposite of knit. Looks like a horizontal bar.", "ko": "겉뜨기의 반대 동작으로 가로줄 모양이 나옵니다."}', 
    'knit', 
    'basic'
),
(
    'yo',
    '{"en": "Yarn Over", "ko": "바늘비우기"}',
    '{"en": "Wrap yarn around needle to create a hole.", "ko": "바늘에 실을 감아 구멍을 만듭니다."}',
    null,
    'basic'
),
(
    'k2tog',
    '{"en": "Knit 2 Together", "ko": "오른코모아뜨기"}',
    '{"en": "Decrease stitch leaning right.", "ko": "두 코를 한꺼번에 겉뜨기하여 코를 줄입니다 (오른쪽 기울기)."}',
    null,
    'decrease'
),
(
    'ssk',
    '{"en": "SSK", "ko": "왼코모아뜨기"}',
    '{"en": "Slip, slip, knit. Decrease leaning left.", "ko": "코를 옮기고 겉뜨기하여 코를 줄입니다 (왼쪽 기울기)."}',
    null,
    'decrease'
);

-- Update antonym link for knit (circular dependency resolution)
update public.stitch_symbols set antonym_id = 'purl' where id = 'knit';


-- Function to handle new user signup
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, email, display_name)
  values (new.id, new.email, split_part(new.email, '@', 1));
  return new;
end;
$$ language plpgsql security definer;

-- Trigger for new user
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 7. REVIEWS (Verified Buyers Only)
create table public.reviews (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references public.profiles(id) not null,
  pattern_id uuid references public.patterns(id) not null,
  rating integer not null check (rating >= 1 and rating <= 5),
  content text not null check (length(content) >= 10),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, pattern_id) -- One review per user per pattern
);

-- RLS for Reviews
alter table public.reviews enable row level security;
create policy "Reviews are viewable by everyone." on reviews for select using (true);
create policy "Users can insert reviews for purchased patterns." on reviews for insert with check (
  auth.uid() = user_id and
  exists (
    select 1 from public.orders
    where orders.user_id = auth.uid()
    and orders.pattern_id = reviews.pattern_id
    and orders.status = 'paid'
  )
);
create policy "Users can update own reviews." on reviews for update using (auth.uid() = user_id);
create policy "Users can delete own reviews." on reviews for delete using (auth.uid() = user_id);

-- 8. FOLLOWS
create table public.follows (
  follower_id uuid references public.profiles(id) not null,
  following_id uuid references public.profiles(id) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  primary key (follower_id, following_id),
  check (follower_id <> following_id)
);

-- RLS for Follows
alter table public.follows enable row level security;
create policy "Follows are viewable by everyone." on follows for select using (true);
create policy "Users can follow others." on follows for insert with check (auth.uid() = follower_id);
create policy "Users can unfollow." on follows for delete using (auth.uid() = follower_id);

-- 9. CREDIT TRANSACTIONS (Coin Economy)
create table public.credit_transactions (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references public.profiles(id) not null,
  amount integer not null, -- Positive for earning, negative for spending
  type text not null check (type in ('earning', 'spending', 'initial_bonus', 'refund')),
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS for Credit Transactions
alter table public.credit_transactions enable row level security;
create policy "Users can view own transactions." on credit_transactions for select using (auth.uid() = user_id);

-- Function to update profile credits automatically
create or replace function public.update_profile_credits() 
returns trigger as $$
begin
  update public.profiles 
  set credits = credits + new.amount
  where id = new.user_id;
  return new;
end;
$$ language plpgsql security definer;

-- Trigger for credit updates
create trigger on_credit_transaction_created
  after insert on public.credit_transactions
  for each row execute procedure public.update_profile_credits();

