import { jsPDF } from 'jspdf';

interface PatternMetadata {
    title: string;
    width: number;
    height: number;
    designer?: string;
    createdAt?: string;
    palette: string[]; // List of colors
}

export const generatePatternPDF = async (
    imgData: string,
    metadata: PatternMetadata,
    stitchSymbols: Record<string, { symbol: string; name: string }>
): Promise<File> => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 20;
    const contentWidth = pageWidth - (margin * 2);

    // 1. Header
    doc.setFillColor(253, 248, 243); // cream-50
    doc.rect(0, 0, pageWidth, 40, 'F');

    doc.setFontSize(24);
    doc.setTextColor(87, 66, 54); // brown-700
    doc.text(metadata.title, margin, 25);

    doc.setFontSize(10);
    doc.setTextColor(140, 120, 110); // brown-500
    const subtitle = `Designed by ${metadata.designer || 'Knitwear Creator'} • ${metadata.createdAt || new Date().toLocaleDateString()}`;
    doc.text(subtitle, margin, 35);

    // 2. Pattern Info Table
    let yPos = 55;
    doc.setFontSize(12);
    doc.setTextColor(87, 66, 54);
    doc.text('Pattern Details', margin, yPos);
    yPos += 10;

    const details = [
        `Size: ${metadata.width} stitches x ${metadata.height} rows`,
        `Colors: ${metadata.palette.length} colors used`
    ];

    details.forEach(detail => {
        doc.setFontSize(10);
        doc.text(`• ${detail}`, margin + 5, yPos);
        yPos += 7;
    });

    // 3. Chart Image
    yPos += 10;
    doc.setFontSize(12);
    doc.text('Chart', margin, yPos);
    yPos += 10;

    // Calculate image dimensions to fit
    const imgProps = doc.getImageProperties(imgData);
    const imgRatio = imgProps.height / imgProps.width;
    let imgHeight = contentWidth * imgRatio;

    // Check if image fits on page, else new page
    if (yPos + imgHeight > pageHeight - margin) {
        // If it's too huge, just constrain it or move to next page
        if (imgHeight > pageHeight - (margin * 2)) {
            // Very tall image - fit to height
            imgHeight = pageHeight - (margin * 2) - 40; // leave some space
            // Recalculate width
            const newWidth = imgHeight / imgRatio;
            // Center it
            doc.addPage();
            doc.addImage(imgData, 'PNG', (pageWidth - newWidth) / 2, margin, newWidth, imgHeight);
        } else {
            doc.addPage();
            doc.addImage(imgData, 'PNG', margin, margin, contentWidth, imgHeight);
        }
    } else {
        doc.addImage(imgData, 'PNG', margin, yPos, contentWidth, imgHeight);
    }

    // 4. Legend (Stitch Key)
    // Add new page for legend if needed (or put below if space, let's just add new page for clarity if chart is big)
    doc.addPage();

    doc.setFontSize(14);
    doc.text('Stitch Key', margin, 30);

    let legendY = 50;
    const boxSize = 10;

    metadata.palette.forEach((color) => {
        const symbolInfo = stitchSymbols[color] || { symbol: '?', name: 'Unknown' };

        // Draw color box
        doc.setFillColor(color);
        doc.setDrawColor(200, 200, 200); // gray border
        doc.rect(margin, legendY, boxSize, boxSize, 'FD');

        // Draw symbol inside
        doc.setTextColor(color === '#FFFFFF' || color === '#F5D0C5' ? 87 : 255, // contrast text
            color === '#FFFFFF' || color === '#F5D0C5' ? 66 : 255,
            color === '#FFFFFF' || color === '#F5D0C5' ? 54 : 255);

        // Simple centering approximation
        doc.setFontSize(8);
        doc.text(symbolInfo.symbol, margin + 4, legendY + 6.5, { align: 'center' });

        // Draw description text
        doc.setTextColor(87, 66, 54); // brown-700
        doc.setFontSize(11);
        doc.text(symbolInfo.name, margin + 20, legendY + 7);

        legendY += 15;
    });

    // Footer
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text(`Page ${i} of ${pageCount} • Generated by Knitwear Platform`, pageWidth / 2, pageHeight - 10, { align: 'center' });
    }

    const blob = doc.output('blob');
    return new File([blob], `${metadata.title.replace(/\s+/g, '_')}.pdf`, { type: 'application/pdf' });
};

export const generateProductDescription = (metadata: PatternMetadata, stitchSymbols: Record<string, { name: string }>): string => {
    // 1. Analyze Pattern
    const stitchNames = Array.from(new Set(
        metadata.palette.map(color => stitchSymbols[color]?.name).filter(Boolean)
    ));
    const width = metadata.width;
    const height = metadata.height;
    const colorCount = metadata.palette.length;
    const uniqueStitches = stitchNames.length;

    // Determine Complexity & Style
    const isComplex = uniqueStitches > 5 || colorCount > 4;
    const isBeginner = uniqueStitches <= 3 && colorCount <= 2;
    const isColorwork = colorCount > 2;

    // 2. Dynamic Opening
    const openings = [
        `Discover the joy of creating with this unique ${width}x${height} knitting chart.`,
        `This custom-designed pattern features a beautiful ${width}-stitch wide motif perfect for your next project.`,
        `Elevate your knitting with this detailed ${colorCount}-color chart design.`,
        `A lovely ${isBeginner ? 'beginner-friendly' : 'intricate'} chart designed for creative knitters.`
    ];
    const opening = openings[Math.floor(Math.random() * openings.length)];

    // 3. Technical Detail Sentence
    const techniqueDesc = isColorwork
        ? `This piece creates a vibrant look using ${colorCount} distinct colors.`
        : `It relies on texture and structure using ${uniqueStitches} different stitch types.`;

    // 4. Usage Suggestion
    const suggestions = [
        "Perfect for incorporating into a sweater yoke, scarf, or cushion cover.",
        "Add this motif to hats, bags, or blankets for a personalized touch.",
        "Ideal for colorwork practice or adding a focal point to plain knits.",
        "Use this chart to customize your favorite basic patterns."
    ];
    const suggestion = suggestions[Math.floor(Math.random() * suggestions.length)];

    // 5. Build Description
    return `
${opening}

${techniqueDesc} ${suggestion}

**Pattern Specifications:**
- **Dimensions:** ${width} stitches x ${height} rows
- **Difficulty:** ${isBeginner ? 'Beginner' : isComplex ? 'Intermediate/Advanced' : 'Intermediate'}
- **Palette:** ${colorCount} colors used
- **Techniques Used:** ${stitchNames.join(', ')}

**What's Included:**
- High-resolution color chart
- Symbol legend (Key) with names
- Optimized PDF for printing or digital viewing

Start knitting this beautiful design today!
    `.trim();
};
